modLoader="javafml"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/Mrbysco/MurderLeaderboard/issues"
license="MIT"

[[mods]]
modId="murderleaderboard"
version="${file.jarVersion}"
displayName="Murder Leaderboard"
displayURL="https://www.curseforge.com/minecraft/mc-mods/murder-leaderboard"
authors="Mrbysco, ShyNieke"
description='''
Do you have some sneaky subs murdering you? Well now you can keep track of who keeps getting you killed!
'''
credits="GenerikB"

[[dependencies.murderleaderboard]]
modId="minecraft"
mandatory=true
versionRange="[1.18,1.19)"
ordering="NONE"
side="BOTH"